### ISSUE TITLE
How to provide train datasets?

### ISSUE THREAD

**Issue by juicebox18** [YukangWang/TextField#1]
Thank you for sharing the approach. 
Could you please give an example or commit a demo on how you provide your datasets for training? Your train.py script used the DataLayer and reads data from data_dir='/home/wangyukang/dataset/' I think? But how is it formatted, what is the structure (image and gt in one folder? gt as images or as txt?)

**Comment by YukangWang** [comment]
Sorry for this abs path. Now it has been replaced by ‘../../data/’ and the dataset should be placed there.

For the given datasets, images and gts are placed in different folders. The format of gt depends on the dataset. For example, .mat for Total-Text and .txt for IC15.

**Comment by juicebox18** [comment]
Thanks, I already found the py scripts that have to be adapted for a new dataset to be added (pylayerUtils.py and datasetUtils.py).
