### ISSUE TITLE
How to make with inference.cpp

### ISSUE THREAD

**Issue by saicoco** [YukangWang/TextField#3]

**Comment by YukangWang** [comment]
If you compile Caffe with "_make all_", this file will be automatically compiled as well.

Or you can use g++ to compile it, here is an example. Note that OpenCV is required.

```g++ `pkg-config opencv --cflags` `pkg-config opencv --libs` inference.cpp -o inference```

**Comment by saicoco** [comment]
thanks, get it

**Comment by saicoco** [comment]
In my case: cuda-8.0 compile it with following code alone:
```
 g++ `pkg-config cublas-8.0 opencv --cflags` `pkg-config cublas-8.0 opencv --libs` inference.cpp -o inference -lboost_system -lglog
```
